// Generated by scripts/fetch-google-rating.mjs — run `pnpm fetch:reviews`
// to refresh the rating/review count from Google. Do not hand-edit the
// rating/reviewCount/googleMapsUri fields; edit CURATED_REVIEWS in the
// script instead, then re-run it.

export type CuratedReview = {
  author: string
  meta: string
  quote: string
}

export const GOOGLE_RATING = {
  rating: 4.9,
  reviewCount: 112,
  googleMapsUri: "https://maps.google.com/?cid=7781375265323095092&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
}

export const CURATED_REVIEWS: CuratedReview[] = [
  {
    "author": "Juliano Marcante",
    "meta": "Local Guide · 36 avaliações",
    "quote": "Ambiente agradável, ótimo atendimento, excelente localização, profissionais competentes. Recomendo."
  },
  {
    "author": "Wilson Schiochet",
    "meta": "Local Guide · 43 avaliações",
    "quote": "Excelentes profissionais, espaço aconchegante, com boas músicas e bate papo descontraído."
  },
  {
    "author": "Victor Terra",
    "meta": "Local Guide · 323 avaliações",
    "quote": "Excelente atendimento, ótimo profissional e preço justo. Recomendo."
  }
]
